name: ll-dm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ocl-icd-system
  - clblast
  - faiss-cpu
  - nb_conda_kernels
  - pip
  - pip:
    - pdm
    - click >= 5.1
variables:
  CMAKE_ARGS: -DLLAMA_CLBLAST=on