name: ll-dm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cuda=12.1
  - cudnn=8
  - nb_conda_kernels
  - pip
  - pip:
    - pdm
    - click >= 5.1
variables:
  CMAKE_ARGS: -DLLAMA_CLBLAST=on
