[project]
name = "ll-dm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Diego Piccinotti", email = "elimdor@live.it"},
]
dependencies = [
    "transformers[torch]>=4.36.2",
    "torch>=2.1.2",
    "torchaudio>=2.1.2",
    "torchvision>=0.16.2",
    "sentencepiece>=0.1.99",
    "accelerate>=0.26.1",
    "chainlit>=1.0.100",
    "langchain>=0.1.0",
    "loguru>=0.7.2",
    "optimum>=1.16.1",
    "llama-cpp-python @ file:///${PROJECT_ROOT}/llama-cpp-python/dist/llama_cpp_python-0.2.28-cp310-cp310-manylinux_2_35_x86_64.whl"
]
requires-python = ">3.8.13,<3.12"
readme = "README.md"
license = {text = "MIT"}

[[tool.pdm.source]]
name = "toch-rocm"
url = "https://download.pytorch.org/whl/rocm5.6"
include_packages = ["torch*"]
# exclude_packages = ["bar-*"]

[tool.pdm]
package-type = "application"
