[project]
name = "ll-dm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Diego Piccinotti", email = "elimdor@live.it"},
]
dependencies = [
    "transformers[torch]>=4.36.2",
    "torch>=2.1.2",
    "torchaudio>=2.1.2",
    "torchvision>=0.16.2",
    "sentencepiece>=0.1.99",
    "accelerate>=0.26.1",
    "chainlit>=1.0.100",
    "langchain>=0.1.0",
    "loguru>=0.7.2",
    "optimum>=1.16.1",
    "llama-cpp-python @ git+https://github.com/abetlen/llama-cpp-python@v0.2.28",
    # "llama-cpp-python @ file:///${PROJECT_ROOT}/whl/llama-cpp-0.2.28-cp310-cp310-linux_x86_64.whl"
    "sentence-transformers>=2.2.2",
    "unstructured>=0.12.0",
    "cohere>=4.42",
]
requires-python = ">=3.10,<3.12"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
notebook = [
    "jupyter>=1.0.0",
    "ipykernel>=6.28.0",
]
[[tool.pdm.source]]
name = "toch-rocm"
url = "https://download.pytorch.org/whl/rocm5.6"
include_packages = ["torch*"]
# exclude_packages = ["bar-*"]

[tool.pdm]
package-type = "application"
